services:
  app:
    build: .
    image: alfifrr/bankingsystem:latest
    ports:
      - 8080:8080
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: 1
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      POSTGRESQL_URL: ${POSTGRESQL_URL}
      FLASK_APP: app
    command: gunicorn --bind 0.0.0.0:8080 --workers 2 "app:create_app()"
#     depends_on:
#       db:
#         condition: service_healthy
#   db:
#     image: postgres
#     environment:
#       POSTGRES_USER: user
#       POSTGRES_PASSWORD: secret
#       POSTGRES_DB: postgres
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U user -d postgres"]
#       interval: 5s
#       timeout: 5s
#       retries: 5
#     volumes:
#       - db_data:/var/lib/postgresql/data
#   adminer:
#     image: adminer
#     ports:
#       - 8080:8080
#     depends_on:
#       - db
# volumes:
#   db_data:
