services:
  app:
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: 1
      JWT_SECRET_KEY: 11c7c47261874573ad3ea79a11dcd471
    command: flask run -h 0.0.0.0
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
  db_data:
