"""update: set default values for existing users

Revision ID: 19ff657cbd77
Revises: 77d75334765b
Create Date: 2025-04-11 22:04:51.961956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19ff657cbd77'
down_revision = '77d75334765b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('UPDATE users SET is_active = TRUE WHERE is_active IS NULL')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_active',
                              existing_type=sa.BOOLEAN(),
                              nullable=False,
                              server_default=sa.text('false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_active',
                              existing_type=sa.BOOLEAN(),
                              nullable=True,
                              server_default=None)

    # ### end Alembic commands ###
