"""empty message

Revision ID: 2f4e3a4a4a03
Revises:
Create Date: 2025-03-23 20:35:09.929650

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2f4e3a4a4a03"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_main", sa.Boolean(), nullable=True))

    op.execute("UPDATE accounts SET is_main = FALSE")

    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.alter_column("is_main", existing_type=sa.Boolean(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.drop_column("is_main")

    # ### end Alembic commands ###
