"""Initial migration

Revision ID: 77d75334765b
Revises: 
Create Date: 2025-04-11 21:51:03.168953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77d75334765b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('activation_token', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['activation_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('activation_token')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
